/// Flutter icons BottomBarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomBarIcons
///      fonts:
///       - asset: fonts/BottomBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomBarIcons {
  BottomBarIcons._();

  static const _kFontFam = 'BottomBarIcons';
  static const _kFontPkg = null;

  static const IconData almond = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruits__1_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carrot = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broccoli = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bananas = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
